name: Build Backend Docker

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'Dockerfile'

jobs:
  build:
    name: Build Backend Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Backend Docker Image
      run: |
        docker build -t rahi4567/techbay-backend:latest .

    - name: Log in to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Backend Image
      run: |
        docker push rahi4567/techbay-backend:latest
